config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root "top#index"
  resources :users, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :password_resets, only: %i[new create edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :username, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_login

  def new; end

  def create 
    @user = User.find_by(email: params[:email])
    @user&.deliver_reset_password_instructions!
    redirect_to login_path
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])
    return not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])
    return not_authenticated if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.change_password(params[:user][:password])
      redirect_to login_path
    else
      render :edit
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :require_login

  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :last_name, :first_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake">
  <head>
    <title>IdealBoss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/password_resets/create.html.erb
<div>
  <h1 class="font-bold text-4xl">PasswordResets#create</h1>
  <p>Find me in app/views/password_resets/create.html.erb</p>
</div>

app/views/password_resets/edit.html.erb
<div class="container">
  <h1><%= t('.title') %></h1>
  <%= form_with model: @user, url: password_reset_path(@token), local: true, data: { turbo: false } do |f| %>
    <div>
      <%= f.label :email %>
      <%= @user.email %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="container">
  <h1><%= t('.title') %></h1>
  <%= form_with url: password_resets_path, local: true, data: { turbo: false } do |f| %>
    <div>
      <%= f.label :email, t(User.human_attribute_name(:email)) %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <%= f.submit t('password_resets.new.submit'), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/password_resets/update.html.erb
<div>
  <h1 class="font-bold text-4xl">PasswordResets#update</h1>
  <p>Find me in app/views/password_resets/update.html.erb</p>
</div>

app/views/top/index.html.erb
<div>
  <h1 class="font-bold text-4xl">理想の上司アプリ</h1>
  <p>使い方</p>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <h1><%= t '.title' %></h1>
  <%= form_with url: login_path, local: true, data: { turbo: false } do |f| %>
    <div class="form-group">
      <%= f.label :email, User.human_attribute_name(:email) %>
      <%= f.email_field :email %>
    </div>
    <div class="form-group">
      <%= f.label :password, User.human_attribute_name(:password) %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit (t 'defaults.login'), class: 'btn btn-primary' %>
  <% end %>
  <div class='text-center'>
    <%= link_to (t '.to_register_page'), new_user_path %>
    <%= link_to (t '.password_forget'), new_password_reset_path %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1><%= t '.title' %></h1>
  <%= form_with model: @user, local: true, data: { turbo: false } do |f| %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= f.submit (t 'defaults.register'), class: 'btn btn-primary' %>
  <% end %>
  <div class='text-center'>
    <%= link_to (t '.to_login_page'), login_path %>
  </div>
</div>